name: Check quotes

on: [ pull_request ]

jobs:
  check-quotes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check diff
        id: check-diff
        run: echo "result=$(git diff @^ -- '*.md' | grep ^+.*[“”])" >> $GITHUB_OUTPUT
      - name: If failed
        if: steps.check-diff.outputs.result
        run: exit 1
